// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AvailabilitySlot struct {
	ID             pgtype.UUID
	UserID         pgtype.UUID
	Weekday        int16
	StartLocalTime pgtype.Time
	EndLocalTime   pgtype.Time
	Timezone       string
	SortOrder      int32
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type MagicLinkToken struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	TokenHash  []byte
	ExpiresAt  pgtype.Timestamptz
	ConsumedAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type Profile struct {
	UserID       pgtype.UUID
	Handle       string
	HandleNorm   string
	BirthYear    pgtype.Int4
	BirthMonth   pgtype.Int2
	CountryCode  pgtype.Text
	Timezone     string
	Discoverable bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type User struct {
	ID          pgtype.UUID
	Email       string
	CreatedAt   pgtype.Timestamptz
	LastLoginAt pgtype.Timestamptz
}

type UserLanguage struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	LanguageCode string
	Level        int16
	IsNative     bool
	IsTarget     bool
	Description  pgtype.Text
	SortOrder    int32
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
